### ISSUE TITLE
symbol names in QSD code generator are not sanitized

### ISSUE THREAD

**Issue by goerz** [mabuchilab/QNET#15]
In symbolic expressions, it is often desirable to use LaTeX strings as a symbol name, so that the symbols are rendered nicely in a notebook. For example,

    k = symbols("\kappa", positive=True)

When such a symbol is defined and translated to QSD code, there is a resulting C++ line

    double \kappa = 2;

which is not valid C++ code. All symbol names must be sanitized to contain only word characters (alphanumeric ASCII symbols and underscores)

**Comment by goerz** [comment]
The problem is actually more fundamental: We need to ensure that in any expression, the sanitized names for any symbols are used.

**Comment by ntezak** [comment]
Actually you can just leave out the backslashes everywhere. It still renders nicely.

**Comment by goerz** [comment]
True, but I frequently like to use more complex LaTeX code such as '\chi^{(1)}_0' for symbol names. In any case, the symbol names can be arbitrary unicode strings, while valid C++ variable names are only a subset of ASCII. So, we can't get around doing some sanitation while deriving variable names from symbol names.
