### ISSUE TITLE
Introduce mechanism to annotate "LocalSpace" objects with more details

### ISSUE THREAD

**Issue by ntezak** [mabuchilab/QNET#19]
Right now every Space is treated as equivalent and only once a basis has been set (with some labels and ordering of states) one can distinguish between different kinds of degrees of freedom such as oscillators (->Fock space), spins (-> angular momentum space, with some J,M=-J,...J) and generalized N-level systems.

We should either allow annotating LocalSpace objects with further data or introduce subclasses for the above cases.

**Comment by goerz** [comment]
Is this still true? I think this may have been fixed by making the Hilbert spaces immutable. If this is still an issue, could you add a (failing) test to illustrate the expected behavior?
