### ISSUE TITLE
Drop Python 2 support

### ISSUE THREAD

**Issue by goerz** [mabuchilab/QNET#23]
Is there any reason not to drop Python 2 support? That is, is anyone using QDYN at the moment in a Python 2 environment (and is waiting for some new features)?

I'm especially interested in using ["keyword-only" arguments](https://www.python.org/dev/peps/pep-3102/), e.g.

```
def simplify(*args, rules=None, check_signature=False, **kwargs):
    ...
def __init__(self, *args, hs=None):
    ...
def __init__(self, name, *, hs=None):
   ...
```

This would allow for more consistency in the interfaces, make signatures more explicit, and eliminate code that would locally process `**kwargs` in Python 2.

Also, I think [type annotations](https://www.python.org/dev/peps/pep-0484/) could be used for signature checking, in conjunction with the [enforce package](https://github.com/RussBaz/enforce)

**Comment by goerz** [comment]
@ntezak what is your verdict on this? I'm refactoring some of the `abstract_algebra` code, and I think making the switch to Python3 only would make things easier. But if you think it's important to keep Python2 for now and only drop it in QDYN 3.0, we could do that too.

**Comment by ntezak** [comment]
Our user base is small and there should not be a ton of people affected, so let's do it.

On Oct 22, 2016, at 10:14 AM, Michael Goerz <notifications@github.com<mailto:notifications@github.com>> wrote:

@ntezakhttps://github.com/ntezak what is your verdict on this? I'm refactoring some of the abstract_algebra code, and I think making the switch to Python3 only would make things easier. But if you think it's important to keep Python2 for now and only drop it in QDYN 3.0, we could do that too.

##
