### ISSUE TITLE
Make Hilbert spaces immutable

### ISSUE THREAD

**Issue by goerz** [mabuchilab/QNET#26]
We could increase efficiency my making all `Expressions` fully immutable. At the moment, Hilbert spaces are still a major "mutable" component, as we can change their basis dynamically. It would be better to fix the basis (or leave an explicitly "undefined" basis) at the time a Hilbert space is instantiated. Changing the basis later on, or attaching a defined basis to a Hilbert space that previously had and undefined basis can be done via `substitute`

**Comment by goerz** [comment]
This would also address #19

**Comment by sritchie-stripe** [comment]
👍  for immutability!
