### ISSUE TITLE
Clarify superoperator ordering

### ISSUE THREAD

**Issue by goerz** [mabuchilab/QNET#47]
The [`SuperOperatorOrderKey`](https://github.com/mabuchilab/QNET/blob/801a810852f3817bc004fc211d3d350e984eb794/qnet/algebra/super_operator_algebra.py#L298) contains [code](https://github.com/mabuchilab/QNET/blob/801a810852f3817bc004fc211d3d350e984eb794/qnet/algebra/super_operator_algebra.py#L323)  that explicitly commutes `SPre` and `SPost` superoperators, even if they operate in the same Hilbert space.

I'm not sure I follow the reasoning behind this.

If I define `SPre = [A, .]`, `SPost = [., C]`, and operators `A, B, C` (all in the same Hilbert space), then

    SPost * SPre * B = [[A, B], C]
    SPre * SPost * B = [A, [B, C]]

I don't see how these are equal in general. According to Jacobi's identity,

    [A, [B, C]] = [[A, B], C] + [B, [A, C]]

but since `A`, `B`, `C` are arbitrary operators, so the second term doesn't vanish. Yet, it looks like the code was added very deliberately (and there's even a [specific test](https://github.com/mabuchilab/QNET/blob/801a810852f3817bc004fc211d3d350e984eb794/tests/algebra/test_super_operator_algebra.py#L148) for it). @ntezak, could you clarify the reasoning behind this?

**Comment by ntezak** [comment]
They are not commutators, just one sided products

**Comment by goerz** [comment]
Thanks!

Major brain fart, sorry!
