### ISSUE TITLE
Qutip conversion does not handle TrivialSpace objects well

### ISSUE THREAD

**Issue by goerz** [mabuchilab/QNET#48]
As reported by James Driver, QNET does not handle the conversion to qutip of objects in `TrivialSpace` very well:

*   converting operators in TrivialSpace does not give a useful error:

        >>> from qnet.convert.to_qutip import convert_to_qutip
        >>> from qnet.algebra.operator_algebra import ZeroOperator
        >>> convert_to_qutip(ZeroOperator)
        Traceback (most recent call last):
        File "<ipython-input-4-6143b5660dbf>", line 1, in <module>
            convert_to_qutip(ZeroOperator)
        File "/Users/goerz/Documents/Programming/github/QNET/qnet/convert/to_qutip.py", line 80, in convert_to_qutip
            for s in full_space.local_factors]
        File "/Users/goerz/anaconda3/lib/python3.5/site-packages/qutip/tensor.py", line 82, in tensor
            raise TypeError("Requires at least one input argument")
        TypeError: Requires at least one input argument

    Note that the only way to do this conversion is to explicitly supply a
proper Hilbert space

        >>> from qnet.algebra.hilbert_space_algebra import LocalSpace
        >>> O = convert_to_qutip(ZeroOperator, full_space=LocalSpace(0, dimension=10))

*   converting SLH objects has the same problem:

        >>> from qnet.circuit_components import mach_zehnder_cc
        >>> from qnet.convert.to_qutip import SLH_to_qutip
        >>> mz = mach_zehnder_cc.MachZehnder('Zender', alpha=1 , phi=0)
        >>> slh = mz.toSLH()
        >>> SLH_to_qutip(slh)
        Traceback (most recent call last):
        File "<ipython-input-12-d6fb7ebbfefa>", line 1, in <module>
            SLH_to_qutip(slh)
        File "/Users/goerz/Documents/Programming/github/QNET/qnet/convert/to_qutip.py", line 139, in SLH_to_qutip
            H = convert_to_qutip(slh.H, full_space)
        File "/Users/goerz/Documents/Programming/github/QNET/qnet/convert/to_qutip.py", line 80, in convert_to_qutip
            for s in full_space.local_factors]
        File "/Users/goerz/anaconda3/lib/python3.5/site-packages/qutip/tensor.py", line 82, in tensor
            raise TypeError("Requires at least one input argument")
        TypeError: Requires at least one input argument

In both cases, the problem should be caught early, and the resulting error message should identify the problem clearly, recommending the use of an explicit `full_space`

**Comment by JMDriver** [comment]
The error seems to particularly disagree with the iteration of full_space.local_factors as the local_factors is a method. When I check the type of my SHL object as such - type(SHL.space.local_factors) it confirms that the local_factors is a method.

convert_to_qutip(expr, full_space, mapping)
     78         return qutip.tensor(
     79             *[qutip.Qobj(csr_matrix((s.get_dimension(), s.get_dimension())))
---> 80               for s in full_space.local_factors]
     81         )
     82     elif isinstance(expr, LocalOperator):

TypeError: 'method' object is not iterable

**Comment by goerz** [comment]
In the latest 'develop' version, local_factors is a property, so that should be fine (maybe you're looking at an older version where it was still a method). The core of the problem is that the SLH object doesn't have an associated non-trivial Hilbert space (thus, `local_factors` is an empty list). There is both a bug in how this is reported, but I'm also concerned about the Lindblad operators being scalars, not operators, in the SLH of the circuit. Investigating this now.

**Comment by JMDriver** [comment]
My apologies, I am currently mainly using an outdated version.
