### ISSUE TITLE
qnet.algebra.operator_algebra.OperatorOrderKey.__str__ missing return string initialization

### ISSUE THREAD

**Issue by bcriger** [mabuchilab/QNET#5]
Hi, 

I just cloned the repo and ran the Jaynes-Cummings Hamiltonian example from [the documentation](http://mabuchilab.github.io/QNET/doc/symbolic_algebra.html). I received an error message ending in:

    /home/dcriger/Documents/Github/QNET/qnet/algebra/operator_algebra.py in     __str__(self)
        973                 ret += r" ({}) ".format(str(o))
        974             else:
    --> 975                 ret += " {}".format(str(o))
        976 
        977         return ret
    
    UnboundLocalError: local variable 'ret' referenced before assignment 

I think `ret` needs to be initialized to an empty string or something, but I thought I'd submit this as an issue, since I'm not that familiar with the code yet. 

Cheers,

Ben

**Comment by ntezak** [comment]
Thanks for the bug report!
