### ISSUE TITLE
_flat_api_tools introduces too much abstraction for linters

### ISSUE THREAD

**Issue by danielwe** [mabuchilab/QNET#81]
The automatic api flattening provided by `_flat_api_tools._import_submodules`
 in the main `__init__.py` is neat, but unfortunately too dynamic for tools like pylint.

Minimal example: save the following as `test.py`,
```python
from qnet import CircuitAlgebra
```
and run `pylint test.py`. Output:
```
...
E:  1, 0: No name 'CircuitAlgebra' in module 'qnet' (no-name-in-module)
...
```

What benefits does `_import_submodules` provide over star imports in `__init__.py`, other than enumerating all the submodules automatically? Maintaining that list manually shouldn't be too much of a burden.

I realize that it also populates `__all__`, which would add a significant maintenance overhead if we were to do it manually. But wouldn't it be functionally equivalent to just get rid of the top level `__all__` _and_ do star imports in the top level `__init.py__`? That way, the result of `from qnet import *` would be the same as `from qnet.submodule import *` for all submodules, and then running the initialization code in `__init.py__`.

**Comment by goerz** [comment]
(Apart from the fact that `CircuitAlgebra` doesn't exist; but the issue also applies to something like `LocalSpace`)

I'd consider this a bug in `pylint` (https://github.com/PyCQA/pylint/issues/413). They're refusing to fix it, but their argument is absolutely misguided. I'm not sure what `pylint` does to determine what symbols are contained in an "external" package without executing an import. That's just fundamentally impossible in Python. I can understand not executing the code that is being linted, but getting information about installed packages "statically" makes no sense.

It's probably a good idea to configure `pylint` to completely suppress this message. Personally, I (respectively the `neomake` vim plugin) use `flake8` as a static linter, which by default doesn't seem to check imports at all (which actually makes sense: it's very hard to tell whether imports are correct; you'd have to assume that all the correct dependencies for the code you're linting are installed in the right version. This isn't necessarily the case, but that doesn't mean there's a problem with the code being linted. Import errors should be caught by tests, not linters).

Aside from that, the purpose of `_import_submodules` is exactly to populate `__all__` correctly. The documentation generator (`apidoc`) heavily relies on this. Also, various (dynamics) introspection tools rely on `__all__`, e.g. in PyCharm.

In principle, I'm open to alternative implementations for populating `__all__`, but maintaining it manually is not really an option.

**Comment by danielwe** [comment]
Cool. (Don't know how `CircuitSymbol` turned into `CircuitAlgebra` while I was formulating the issue.)

I guess dynamically defining module level symbols is not too common in the wild, so pylint usually gets away with assuming that the static approach is sufficient. Not so with QNET. I'll disable this message from now on.

**Comment by goerz** [comment]
It's actually not that uncommon, hence a number of bug reports with regards to `pylint` complaining about it.  ;-)

https://github.com/PyCQA/pylint/issues/2392 is another one
